
# app: 
service: insta-ritter-grp3 # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10

stage: dev
region: us-east-1

functions:
  photos:
    handler: src/back/app/handler.photos
    events: 
      - http:
          path: photos
          method: get
          cors: true
  
  photoById:
    handler: src/back/app/handler.photoById
    events: 
      - http:
          path: photos/{photo_id}
          method: get
          cors: true
          request: 
            parameters:
              paths:
                photo_id: true
  # TODO LUCAS: https://github.com/deliveryhero/serverless-aws-documentation
  photo:
    handler: src/back/app/handler.photo
    events: 
      - http:
          path: photo
          method: post
          cors: true                
