
# app: 
service: insta-ritter-grp3 # NOTE: update this with your service name
# tenant: lucastagliani

provider:
  name: aws
  runtime: nodejs6.10

stage: dev
region: us-east-1

functions:
  photos:
    handler: handler.photos
    events: 
      - http:
          path: photos
          method: get
          cors: true
  
  photoById:
    handler: handler.photoById
    events: 
      - http:
          path: photos/{photo_id}
          method: get
          cors: true
          request: 
            parameters:
              paths:
                photo_id: true
                
